sudo: required
dist: trusty

stages:
  - build-and-deploy # lint code and docs

language: node_js

node_js: 
  - "10"

jobs:
  include:
    - stage: build-and-deploy
      name: 'Build + Deploy'
      script:
        - echo "hi"
      cache:
        yarn: true
        directories:
          - node_modules
          
    - stage: build-and-deploy
      name: 'Build + Deploy2'
      script:
        - echo "hi 2"
        - exit 1
      cache:
        yarn: true
        directories:
          - node_modules
      
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email:
    on_success: never
    on_failure: never

